# Generated by Django 3.2.7 on 2021-09-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('postimage', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
