# Generated by Django 3.2.7 on 2021-09-28 06:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='postimage',
            field=models.ImageField(blank=True, null=True, upload_to='postImages'),
        ),
    ]
