# Generated by Django 3.2.7 on 2021-10-02 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_helpcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='helpComment',
        ),
    ]
